### ISSUE TITLE
请教一下这两个参数为什么不起作用

### ISSUE THREAD

**Issue by zongren** [godlikewangjun/dexknife-wj#7]
这两个参数如下所示
```
archiveOutput = file(new File(project.rootDir.path,"release"))
archiveNameFormat = 'mkb_cz_v${versionName}'
```
![qq 20170704164204](https://user-images.githubusercontent.com/4525819/27822296-c442bd6a-60d7-11e7-8edb-e4fa7172f749.png)
![qq 20170704164212](https://user-images.githubusercontent.com/4525819/27822297-c47f47d0-60d7-11e7-8e2a-ba9d2162b39b.png)
打包生成的apk仍然在`app/build/outputs/apk`目录下

**Comment by godlikewangjun** [comment]
要重新sync build.gradle。没有填写加固名称会默认的 不是加固前的名称一样，你可以解压看结构就知道是否成功。

**Comment by zongren** [comment]
@godlikewangjun 
确实加固成功了
我已经重新执行`sync gradle`了
我的意思是，按照我写的参数，加固后的`apk文件`不应该出现在`release/`目录下，并且命名为`mkb_cz_v1.0.0.apk`吗

**Comment by godlikewangjun** [comment]
意思其实就是没有加固的apk在哪里 加固后的也就在哪里并不会路径。命名不会修改只会追加。如果只想用加固可与命令打包的。绑定编译过程的只有插件里面的多渠道打包
